using NUnit.Framework;

using TransliterationAPI.Service.Transliterators;

namespace TransliterationAPI.UnitTests.Service.Transliterators
{
    public class AncientGreekTransliteratorTests
    {
        private IAncientGreekTransliterator transliterator;

        [SetUp]
        public void SetUp()
        {
            this.transliterator = new AncientGreekTransliterator();
        }

        [Test]
        [TestCase("Kαταoνία", "Kataonía")]
        [TestCase("ᾈγίοι Ανάργυροι", "Agíoi Anárgyroi")]
        [TestCase("Ἀθῆναι", "Athênai")]
        [TestCase("Ᾰθῆναι", "Athênai")]
        [TestCase("Ἀίγινα", "Aígina")]
        [TestCase("Ἀίγυπτος", "Aígyptos")]
        [TestCase("Ᾰκρόπολις", "Akrópolis")]
        [TestCase("Ἀλεξάνδρεια", "Alexándreia")]
        [TestCase("Ἁμανός", "Amanós")]
        [TestCase("Ἄνδρος", "Ándros")]
        [TestCase("Ἀντιόχεια τῆς Μυγδονίας", "Antiókheia tês Mygdonías")]
        [TestCase("Αντίταυρος", "Antítauros")]
        [TestCase("Ᾰπολλωνία", "Apollōnía")]
        [TestCase("Ἀραβισσός", "Arabissós")]
        [TestCase("Ἄργος", "Árgos")]
        [TestCase("Ἀρκαδία", "Arkadía")]
        [TestCase("Ἄρτα", "Árta")]
        [TestCase("Ασκαλων", "Askalōn")]
        [TestCase("Ἄστυπαλαια", "Ástypalaia")]
        [TestCase("Αττική", "Attikḗ")]
        [TestCase("Ἀχαία", "Akhaía")]
        [TestCase("Βαβυλών", "Babylṓn")]
        [TestCase("Βυζάντιον", "Byzántion")]
        [TestCase("Δαμασκός", "Damaskós")]
        [TestCase("Δελφοί", "Delphoí")]
        [TestCase("Δωδώνη", "Dōdṓnē")]
        [TestCase("Ελευσίσ", "Eleusís")]
        [TestCase("Ἐλευσίς", "Eleusís")]
        [TestCase("Ἐπίδαυρος", "Epídauros")]
        [TestCase("Ἐρέτρια", "Erétria")]
        [TestCase("Ἐτεόκρητη", "Eteókrētē")]
        [TestCase("Εὐφράτης", "Euphrátēs")]
        [TestCase("Ήπειρος", "Ḗpeiros")]
        [TestCase("Ἡράκλεια Σιντική", "Hērákleia Sintikḗ")]
        [TestCase("Ἡράκλεια", "Hērákleia")]
        [TestCase("Ἡράκλειον", "Hērákleion")]
        [TestCase("Ἡφαιστία", "Hēphaistía")]
        [TestCase("Θεσσαλονίκη", "Thessaloníkē")]
        [TestCase("Θῆβαι", "Thēbai")]
        [TestCase("Θῆβαι", "Thēbai")]
        [TestCase("Ἱεράπολις", "Hierápolis")]
        [TestCase("Ἰουερνία", "Iouernía")]
        [TestCase("Ἰουερνίς", "Iouernís")]
        [TestCase("Ἰταβύριον", "Itabýrion")]
        [TestCase("Καππαδοκία", "Kappadokía")]
        [TestCase("Κασθαναία", "Kasthanaía")]
        [TestCase("Κασσώπη", "Kassṓpē")]
        [TestCase("Κασταναία", "Kastanaía")]
        [TestCase("Κερύνεια", "Kerýneia")]
        [TestCase("Κεφαλληνία", "Kephallēnía")]
        [TestCase("Κλύσμα", "Klýsma")]
        [TestCase("Κνωσός", "Knōsós")]
        [TestCase("Κόρινθος", "Kórinthos")]
        [TestCase("Κορόπη", "Korópē")]
        [TestCase("Κορυτσά", "Korytsá")]
        [TestCase("Κορωνέα", "Korōnéa")]
        [TestCase("Κορώνη", "Korṓnē")]
        [TestCase("Κουλουκιά", "Kouloukiá")]
        [TestCase("Κρήτη", "Krḗtē")]
        [TestCase("Κρούσεβατς", "Kroúsevats")]
        [TestCase("Κύθηρα", "Kýthēra")]
        [TestCase("Κυλλήνη", "Kyllḗnē")]
        [TestCase("Κύπρος", "Kýpros")]
        [TestCase("Κυρήνη", "Kyrḗnē")]
        [TestCase("Κωνσταντινούπολις", "Kōnstantinoúpolis")]
        [TestCase("Λέσβος", "Lésbos")]
        [TestCase("Λυκανδός", "Lykandós")]
        [TestCase("Μακεδονία", "Makedonía")]
        [TestCase("Μαντίνεια", "Mantíneia")]
        [TestCase("Μελιτηνή", "Melitēnḗ")]
        [TestCase("Μεσσήνη", "Messḗnē")]
        [TestCase("Μίλητος", "Mílētos")]
        [TestCase("Μυγδονία", "Mygdonía")]
        [TestCase("Νάξος", "Náxos")]
        [TestCase("Νέα Κόρινθος", "Néa Kórinthos")]
        [TestCase("Νεάπολις", "Neápolis")]
        [TestCase("Ολυμπία", "Olympía")]
        [TestCase("Ὄλυνθος", "Ólynthos")]
        [TestCase("Οὐινδόβονα", "Ouindóbona")]
        [TestCase("Παλαιστίνη", "Palaistínē")]
        [TestCase("Παλλήνη", "Pallḗnē")]
        [TestCase("Πανόπολις", "Panópolis")]
        [TestCase("Πανὸς πόλις", "Panὸs pólis")]
        [TestCase("Παραλία", "Paralía")]
        [TestCase("Πελοπόννησος", "Pelopónnēsos")]
        [TestCase("Ῥόδος", "Rhódos")]
        [TestCase("Ῥώμη", "Rhṓmē")]
        [TestCase("Σάρος", "Sáros")]
        [TestCase("Σπάρτη", "Spártē")]
        [TestCase("Συήνη", "Suḗnē")]
        [TestCase("Φιλαδέλφεια", "Philadélpheia")]
        [TestCase("Χαλάστρα", "Khalástra")]
        [TestCase("Χαλέστρη", "Khaléstrē")]
        [TestCase("Χαλκιδική", "Khalkidikḗ")]
        [TestCase("Χέμμις", "Khémmis")]
        public void GivenATextInAncientGreekScript_WhenTransliteratingIntoLatin_ThenTheCorrectTextIsReturned(
            string ancientGreekText,
            string expectedTransliteratedText)
            => Assert.That(transliterator.Transliterate(ancientGreekText, "grc"), Is.EqualTo(expectedTransliteratedText));

        [Test]
        [TestCase("Ᾰθῆναι", "Athênai")]
        [TestCase("Αττική", "Attiká")]
        [TestCase("Δᾶλος", "Dâlos")]
        [TestCase("Ἐτεόκρητη", "Eteókrēta")]
        [TestCase("Ήπειρος", "Ápeiros")]
        [TestCase("Ἡράκλεια Σιντική", "Hērákleia Sintiká")]
        [TestCase("Ἡφαιστία", "Haphaistía")]
        [TestCase("Κασσώπη", "Kassṓpa")]
        [TestCase("Κερύνεια", "Karýneia")]
        [TestCase("Κεφαλληνία", "Kephallanía")]
        [TestCase("Κορόπη", "Korópa")]
        [TestCase("Κορώνη", "Korṓna")]
        [TestCase("Κρήτη", "Krḗta")]
        [TestCase("Κυλλήνη", "Kyllána")]
        [TestCase("Μαντίνεια", "Mantinéa")]
        [TestCase("Παλλήνη", "Pallána")]
        [TestCase("Χαλκιδική", "Khalkidiká")]
        public void GivenATextInAncientGreekDoricScript_WhenTransliteratingIntoLatin_ThenTheCorrectTextIsReturned(
            string ancientGreekDoricText,
            string expectedTransliteratedText)
            => Assert.That(transliterator.Transliterate(ancientGreekDoricText, "grc-dor"), Is.EqualTo(expectedTransliteratedText));
    }
}
